apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-auth
  name: mongodb-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-auth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-auth
    spec:
      containers:
        - image: mongo:latest
          name: mongodb-auth
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: data-auth
      restartPolicy: Always
      volumes:
        - name: data-auth
          persistentVolumeClaim:
            claimName: data-auth
status: {}
